version: "3.3"

services:
  db:
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_server_data:/var/lib/mysql
    restart: always
    env_file: ./env_files/.env_mysql
    ports:
      - 3306:3306
    networks:
      - database_network
  
  fastapi-backend:
    build:
      context: .
      dockerfile: ./docker/fastapi_backend/Dockerfile
    container_name: fastapi-backend-container
    restart: always
    ports:
      - 8000:8000
    networks:
      - backend_network

volumes:
  mysql_server_data:

networks:
  database_network:
    name: mysql_network
    driver: bridge
  backend_network:
    name: backend_network
    driver: bridge