#! /bin/bash
# program to output system information page

echo "<html>"
echo "	<head>"
echo "		<title>Page Title</title>"
echo "	</head>"
echo "	<body>"
echo "		page body."
echo "	</body>"
echo "</html>"
