#! /bin/bash
title="System Information Page"
variable="$(ls -ll)"
declare -r TITLE="Read ONLY title"
echo "<html>
	<head>
		<title>$title</title>
	</head>
	<body>
		$title
		$PATH
		<h1>$TITLE</h1>
		<p>$variable</p>
	</body>
</html>"
